name: tts_flutter_online_azure
description: tts flutter online azure service for app.

version: 1.0.0+1

environment:
  sdk: ^3.4.0-0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  auto_route: ^7.8.4
  sqflite: ^2.4.1
  path_provider: ^2.1.2
  hive: ^2.2.3
  just_audio: 0.9.46

dev_dependencies:
  build_runner: 2.4.14
  json_serializable: 6.9.0
  auto_route_generator: 7.3.2

flutter:
  module:
    androidPackage: tss_multi_fun.tts_flutter_online_elevenlabs.module
    iosBundleIdentifier: tss_multi_fun.tts_flutter_online_elevenlabs.module