name: tts_flutter_online_elevenlabs
description: tts flutter online elevenlabs service for app.

version: 1.0.0+1

environment:
  sdk: ^3.4.0-0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  auto_route: ^7.8.4
  flutter_sound: 9.23.1
  sqflite: ^2.4.1
  path_provider: ^2.1.2
  hive: ^2.2.3
  intl: 0.20.2
  permission_handler: 11.3.1
  lottie: 3.3.1
  ffmpeg_kit_flutter_full_gpl: 6.0.3

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.6.1

flutter:
  module:
    androidPackage: tss_multi_fun.tts_flutter_online_elevenlabs.module
    iosBundleIdentifier: tss_multi_fun.tts_flutter_online_elevenlabs.module

  assets:
    - assets/record_imitation_scene.json
    - assets/playing_imitation_scene.json